# -*- coding: utf-8 -*-
"""App for simple regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbDNs7DU6GZHc2YjwdNDcrZwR2MKassd
"""
import streamlit as st
import numpy as np
import plotly.graph_objects as go

# Set page configuration
st.set_page_config(page_title="Interactive Regression Plot", layout="centered")

# Title and description
st.title("Interactive Linear Regression Plot")
st.write("Adjust the slope and intercept to see how the regression line changes.")

# Generate sample data
np.random.seed(42)
x = np.linspace(0, 10, 50)
y = 2 * x + 1 + np.random.normal(0, 1, 50)

# Create sliders for slope and intercept
slope = st.slider("Slope", min_value=-5.0, max_value=5.0, value=2.0, step=0.1)
intercept = st.slider("Intercept", min_value=-10.0, max_value=10.0, value=1.0, step=0.1)

# Calculate regression line
y_pred = slope * x + intercept

# Create Plotly figure
fig = go.Figure()

# Add scatter plot of data points
fig.add_trace(
    go.Scatter(x=x, y=y, mode="markers", name="Data Points", marker=dict(size=8))
)

# Add regression line
fig.add_trace(
    go.Scatter(x=x, y=y_pred, mode="lines", name=f"y = {slope:.1f}x + {intercept:.1f}", line=dict(color="red"))
)

# Update layout
fig.update_layout(
    title="Linear Regression",
    xaxis_title="X",
    yaxis_title="Y",
    showlegend=True,
    width=600,
    height=400
)

# Display plot
st.plotly_chart(fig)

# Display equation
st.write(f"**Current Equation**: y = {slope:.1f}x + {intercept:.1f}")
