# -*- coding: utf-8 -*-
"""App for simple regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbDNs7DU6GZHc2YjwdNDcrZwR2MKassd
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.title('Simple Linear Regression with Interactive Widgets')

# Generate some sample data
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

st.write("This app demonstrates simple linear regression. You can adjust the intercept and slope using the sliders below to see how the regression line changes.")

# Create interactive widgets for intercept and slope
st.sidebar.header('Model Parameters')
intercept = st.sidebar.slider('Intercept', -10.0, 10.0, 4.0, 0.1)
slope = st.sidebar.slider('Slope', -10.0, 10.0, 3.0, 0.1)

# Calculate the predicted y values based on the current intercept and slope
y_pred = intercept + slope * X

# Plot the data points and the regression line
fig, ax = plt.subplots()
ax.scatter(X, y, label='Data Points')
ax.plot(X, y_pred, color='red', label='Regression Line')
ax.set_xlabel('X')
ax.set_ylabel('y')
ax.set_title('Simple Linear Regression')
ax.legend()
st.pyplot(fig)

st.write("The red line represents the regression line with the selected intercept and slope.")
