# -*- coding: utf-8 -*-
"""Quiz regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZ42V1481tpWEDRPnvMcCJCjOXOEP-pq
"""

# prompt: install streamlit

!pip install streamlit -q

import streamlit as st

st.set_page_config(page_title="Finance Regression Quiz", layout="centered")

st.title("📊 Quiz: Regression Models in Finance")
st.write("Test your understanding of regression models and their applications in finance.")

# Define questions and answers
questions = [
    {
        "question": "1. What is the main purpose of a regression model in finance?",
        "options": ["A) To create marketing campaigns", "B) To explain or predict the relationship between variables",
                    "C) To eliminate all financial risks", "D) To record accounting data"],
        "answer": "B) To explain or predict the relationship between variables"
    },
    {
        "question": "2. In a simple linear regression model, which of the following is typically the dependent variable?",
        "options": ["A) Interest rates", "B) Earnings per share", "C) Stock price", "D) Market capitalization"],
        "answer": "C) Stock price"
    },
    {
        "question": "3. In the equation StockPriceᵢ = β₀ + β₁·EPSᵢ + uᵢ, what does β₁ represent?",
        "options": ["A) The average stock price", "B) The rate of inflation",
                    "C) The effect of a one-unit change in EPS on stock price", "D) The error in the model"],
        "answer": "C) The effect of a one-unit change in EPS on stock price"
    },
    {
        "question": "4. What does the error term uᵢ in a regression equation represent?",
        "options": ["A) A mathematical mistake", "B) The explanatory variable",
                    "C) Factors not included in the model that affect the dependent variable", "D) Random numbers added for balance"],
        "answer": "C) Factors not included in the model that affect the dependent variable"
    },
    {
        "question": "5. Why might we prefer multiple regression over simple regression in finance?",
        "options": ["A) It guarantees accurate predictions", "B) It can account for multiple factors that affect the outcome",
                    "C) It’s faster to calculate", "D) It eliminates the error term"],
        "answer": "B) It can account for multiple factors that affect the outcome"
    },
    {
        "question": "6. In the equation StockReturnᵢ = β₀ + β₁·MarketReturnᵢ + β₂·Sizeᵢ + β₃·DebtRatioᵢ + uᵢ, which variable is NOT an explanatory variable?",
        "options": ["A) Sizeᵢ", "B) StockReturnᵢ", "C) MarketReturnᵢ", "D) DebtRatioᵢ"],
        "answer": "B) StockReturnᵢ"
    },
    {
        "question": "7. What does a positive value for β₃ in the previous model suggest about debt ratio and stock return?",
        "options": ["A) Higher debt is associated with lower stock returns", "B) The model is invalid",
                    "C) Higher debt is associated with higher stock returns", "D) Debt ratio has no effect"],
        "answer": "C) Higher debt is associated with higher stock returns"
    },
    {
        "question": "8. What is one major use of regression in financial institutions like banks?",
        "options": ["A) Printing statements", "B) Predicting customer birthdays",
                    "C) Estimating credit risk or default probability", "D) Issuing stock options"],
        "answer": "C) Estimating credit risk or default probability"
    },
    {
        "question": "9. What is one limitation of regression models that Wooldridge warns about?",
        "options": ["A) They are only usable in marketing", "B) They work only with perfect data",
                    "C) They can be misleading if important variables are left out", "D) They never require validation"],
        "answer": "C) They can be misleading if important variables are left out"
    },
    {
        "question": "10. Which best describes the relationship between market return and stock return if β₁ is close to 1?",
        "options": ["A) No relationship", "B) The stock return moves in the same direction and magnitude as the market return",
                    "C) The stock always outperforms the market", "D) The market return has no effect on the stock"],
        "answer": "B) The stock return moves in the same direction and magnitude as the market return"
    }
]

# Create a form to submit answers
with st.form("quiz_form"):
    user_answers = []
    for i, q in enumerate(questions):
        st.markdown(f"**{q['question']}**")
        user_answer = st.radio(f"Select your answer:", q["options"], key=f"q{i}")
        user_answers.append(user_answer)
        st.markdown("---")

    submitted = st.form_submit_button("Submit Answers")

# Evaluate and display score
if submitted:
    score = 0
    st.subheader("📋 Results:")
    for i, q in enumerate(questions):
        correct = q["answer"]
        user = user_answers[i]
        if user == correct:
            st.success(f"✅ Question {i+1}: Correct")
            score += 1
        else:
            st.error(f"❌ Question {i+1}: Incorrect. Correct answer: {correct}")

    st.markdown(f"### 🧠 Your Total Score: **{score} / {len(questions)}**")